// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSoat.Persistencia;

#nullable disable

namespace WebApiSoat.Persistencia.Migrations
{
    [DbContext(typeof(DbSoatContext))]
    partial class DbSoatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiSoat.Core.Modelos.CiudadVenta", b =>
                {
                    b.Property<int>("IdCiudadVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiudadVenta"), 1L, 1);

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Permitido")
                        .HasColumnType("bit");

                    b.HasKey("IdCiudadVenta");

                    b.ToTable("CiudadVenta", "dbo");
                });

            modelBuilder.Entity("WebApiSoat.Core.Modelos.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"), 1L, 1);

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente", "dbo");
                });

            modelBuilder.Entity("WebApiSoat.Core.Modelos.Soat", b =>
                {
                    b.Property<int>("IdSoat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSoat"), 1L, 1);

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVenciminetoPolizaActual")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCiudadVenta")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("IdCliente");

                    b.Property<string>("PlacaAutomotor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSoat");

                    b.HasIndex("IdCliente");

                    b.ToTable("Soat", "dbo");
                });

            modelBuilder.Entity("WebApiSoat.Core.Modelos.Soat", b =>
                {
                    b.HasOne("WebApiSoat.Core.Modelos.Cliente", "Cliente")
                        .WithMany("Soats")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("WebApiSoat.Core.Modelos.Cliente", b =>
                {
                    b.Navigation("Soats");
                });
#pragma warning restore 612, 618
        }
    }
}
